### PR TITLE
Withoutnew

### PR DESCRIPTION
**Pull request by robreczarek**
This code resolves all remaining issues and closes out the project

### CODE REVIEW

**Comment by piecioshka** [comment]
@robreczarek keep going!

**Comment by robreczarek** [comment]
@piecioshka Is there something missing or do you mean to move onto the next project?

**Comment by piecioshka** [comment]
@robreczarek to znaczy, żebyś nie odpuszczał programowania i robił nowe projekty, bo zauważyłem, że przez kilka dni bezczynność w tej kwestii 😄

**Comment by robreczarek** [comment]
@piecioshka I got sick, which is also why I didn't make it to the workshop :( Still feeling the aftereffects, but will be at WarsawJS ;) Thanks for keeping an eye on me!

**Pull request merged**
